In [37]:
import pandas as pd




behaviour_df=pd.read_csv("dataset/customer_shopping_behavior.csv")

In [38]:
behaviour_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [39]:
behaviour_df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [40]:
behaviour_df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [41]:
behaviour_df['Review Rating']=behaviour_df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [42]:
behaviour_df.columns=behaviour_df.columns.str.lower()
behaviour_df.columns=behaviour_df.columns.str.replace(' ','_')

In [43]:
behaviour_df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [44]:
behaviour_df= behaviour_df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [45]:
behaviour_df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [46]:


#Feature engineering

#1)Create new column for age group
labels=["Young Adult","Adult","Middle-Aged","Elderly"]
behaviour_df['age_group']=pd.qcut(behaviour_df['age'],q=4,labels=labels)


behaviour_df.head(20)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-Aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-Aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-Aged
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly,Middle-Aged
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly,Elderly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly,Young Adult
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually,Young Adult
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly,Middle-Aged
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly,Middle-Aged
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,Yes,10,Bank Transfer,Fortnightly,Young Adult
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,Yes,37,Venmo,Fortnightly,Elderly
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,Yes,31,PayPal,Weekly,Elderly
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,Yes,34,Debit Card,Weekly,Elderly
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,Yes,8,PayPal,Monthly,Elderly
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,Yes,44,Debit Card,Bi-Weekly,Young Adult
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,Yes,36,Venmo,Quarterly,Middle-Aged
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,Yes,17,Cash,Weekly,Middle-Aged
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,Yes,46,Debit Card,Bi-Weekly,Elderly

In [47]:
#2)Create a column of purchase frequency days

days = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
behaviour_df['purchase_frequency_days']= behaviour_df['frequency_of_purchases'].map(days)

In [48]:
behaviour_df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-Aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-Aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-Aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly,Middle-Aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly,Elderly,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly,Young Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually,Young Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly,Middle-Aged,90

In [49]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\al\desktop\customerbehaviouranalytics\.venv\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\al\desktop\customerbehaviouranalytics\.venv\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\al\desktop\customerbehaviouranalytics\.venv\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\al\desktop\customerbehaviouranalytics\.venv\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
import pandas as pd
from sqlalchemy import create_engine


engine = create_engine("postgresql+psycopg2://postgres:password@localhost/postgres")



# --- Step 2: Write DataFrame to PostgreSQL ---
# This will create a table named 'people' in the 'public' schema
behaviour_df.to_sql("customer", engine, if_exists="replace", index=False)
print("\n✅ DataFrame successfully written to PostgreSQL table 'cusstomer'.")

#Step 3: Read back from PostgreSQL ---
query = "SELECT * FROM customer;"
df_from_db = pd.read_sql(query, engine)
print("\n✅ Data fetched back from PostgreSQL:")
print(df_from_db)

✅ DataFrame successfully written to PostgreSQL table 'cusstomer'.

✅ Data fetched back from PostgreSQL:
      customer_id  age  gender item_purchased     category  purchase_amount  \
0               1   55    Male         Blouse     Clothing               53
1               2   19    Male        Sweater     Clothing               64
2               3   50    Male          Jeans     Clothing               73
3               4   21    Male        Sandals     Footwear               90
4               5   45    Male         Blouse     Clothing               49
...           ...  ...     ...            ...          ...              ...
3895         3896   40  Female         Hoodie     Clothing               28
3896         3897   52  Female       Backpack  Accessories               49
3897         3898   46  Female           Belt  Accessories               33
3898         3899   44  Female          Shoes     Footwear               77
3899         3900   52  Female        Handbag  Accessories               81

           location size      color  season  review_rating  \
0          Kentucky    L       Gray  Winter            3.1
1             Maine    L     Maroon  Winter            3.1
2     Massachusetts    S     Maroon  Spring            3.1
3      Rhode Island    M     Maroon  Spring            3.5
4            Oregon    M  Turquoise  Spring            2.7
...             ...  ...        ...     ...            ...
3895       Virginia    L  Turquoise  Summer            4.2
3896           Iowa    L      White  Spring            4.5
3897     New Jersey    L      Green  Spring            2.9
3898      Minnesota    S      Brown  Summer            3.8
3899     California    M      Beige  Spring            3.1

     subscription_status   shipping_type discount_applied promo_code_used  \
0                    Yes         Express              Yes             Yes
1                    Yes         Express              Yes             Yes
2                    Yes   Free Shipping              Yes             Yes
3                    Yes    Next Day Air              Yes             Yes
4                    Yes   Free Shipping              Yes             Yes
...                  ...             ...              ...             ...
3895                  No  2-Day Shipping               No              No
3896                  No    Store Pickup               No              No
3897                  No        Standard               No              No
3898                  No         Express               No              No
3899                  No    Store Pickup               No              No

      previous_purchases payment_method frequency_of_purchases    age_group  \
0                     14          Venmo            Fortnightly  Middle-Aged
1                      2           Cash            Fortnightly  Young Adult
2                     23    Credit Card                 Weekly  Middle-Aged
3                     49         PayPal                 Weekly  Young Adult
4                     31         PayPal               Annually  Middle-Aged
...                  ...            ...                    ...          ...
3895                  32          Venmo                 Weekly        Adult
3896                  41  Bank Transfer              Bi-Weekly  Middle-Aged
3897                  24          Venmo              Quarterly  Middle-Aged
3898                  24          Venmo                 Weekly        Adult
3899                  33          Venmo              Quarterly  Middle-Aged

      purchase_frequency_days
0                          14
1                          14
2                           7
3                           7
4                         365
...                       ...
3895                        7
3896                       14
3897                       90
3898                        7
3899                       90

[3900 rows x 20 columns]

In [51]:
# Save preprocessed DataFrame as CSV
behaviour_df.to_csv("cleaned_processed_customer_data.csv", index=False)